---
- name: install nginx config
  become: yes
  template:
    src: wordpress
    dest: /etc/nginx/sites-available/wordpress
  notify: restart nginx
  
- name: activate site configuration
  become: yes
  shell: "sudo ln -sf /etc/nginx/sites-available/wordpress /etc/nginx/sites-enabled/"
  notify: restart nginx

- name: download WordPress
  get_url:
    url: "{{ download_url }}"
    dest: "/tmp/latest.tar.gz"

- name: creating directory for WordPress
  file:
    path: "/var/www/wordpress"
    state: "directory"
    owner: "www-data"
    group: "www-data"

- name: unpack WordPress installation
  shell: "tar xvfz /tmp/latest.tar.gz -C /var/www/ && chown -R www-data:www-data /var/www/wordpress"
  
########## user//5t1ah1P8RZN(q039