---
- name: Copy authorized_keys to servers
  become: yes
  ansible.builtin.copy:
    src: authorized_keys
    dest: /home/ubuntu/.ssh/authorized_keys
    owner: ubuntu
    group: ubuntu
    mode: '0400'
    
#TODO разобраться с файлом hosts