---
- name: Install MySQL
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - python3-mysqldb
    - mysql-server-8.0

- name: Start the MySQL service
  action: service name=mysql state=started
  
- name: create user mysql
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    priv: '*.*:ALL'
    host: '%'
    state: present
    check_implicit_admin: true
    login_unix_socket: /var/run/mysqld/mysqld.sock
    
- name: Create a new database
  mysql_db:
    name: wordpress
    state: present
    check_implicit_admin: true
    login_unix_socket: /var/run/mysqld/mysqld.sock
    
- name: update node_exporter.service.j2.j2
  become: yes
  template:
    src: node_exporter.service.j2.j2
    dest: /etc/mysql/mysql.conf.d/node_exporter.service.j2.j2
    
- name: Start the MySQL service
  action: service name=mysql state=restarted
