- name: установка wordpress
  hosts: test
  become: yes
  vars:
    - mysql_root_password: "5t1ah1P8RZN(q039"
    - download_url: "http://wordpress.org/latest.tar.gz"
  roles:
    - nginx
    - php5
    - wordpress
